export type Language = "en" | "ar";

/**
 * All user-facing copy lives here.
 *
 * Writing rules for this file:
 *  - Say the thing. No "leveraging cutting-edge solutions".
 *  - Every label tells the user what happens when they act on it.
 *  - Numbers are real and checkable against constants/index.ts.
 */
export const languages = {
  en: {
    name: "English",
    short: "EN",
    dir: "ltr",
    translations: {
      nav: {
        home: "Home",
        work: "Work",
        about: "About",
        contact: "Contact",
        menu: "Menu",
        close: "Close",
      },
      status: {
        available: "Available for work",
        location: "Riyadh · GMT+3",
      },
      cta: {
        seeWork: "See the work",
        downloadResume: "Download CV",
        backHome: "Back to home",
        copyEmail: "Copy email",
        copied: "Email copied",
        copyFailed: "Couldn't copy — the address is ghzielmorhaf@gmail.com",
      },
      hero: {
        fullName: "Murhaf Ghziel",
        line1: "Full-stack",
        line2: "developer",
        line3: "who ships.",
        lead: "I'm Murhaf. I design and build web apps end to end — React, Next.js and TypeScript on the front, APIs and databases behind them. Five years in, 15 projects shipped, 6 of them paid client builds.",
        alt: "Portrait of Murhaf Ghziel",
      },
      ledger: {
        years: "Years shipping",
        projects: "Projects built",
        clients: "Client builds",
        reply: "Email reply time",
        replyValue: "< 24h",
      },
      work: {
        index: "02",
        eyebrow: "Selected work",
        heading: "Everything I've built, newest first.",
        help: "Hover a row to preview it. Click to read how it was built.",
        helpTouch: "Tap a row to read how it was built.",
        filters: {
          all: "All",
          client: "Client work",
          job: "Full-time",
          practice: "Practice",
        },
        kind: {
          client: "Client",
          job: "Full-time",
          practice: "Practice",
        },
        empty: "Nothing in this filter yet.",
        showAll: "Show the rest",
        kindLabel: "Type",
        role: "Role",
        year: "Year",
        overview: "Overview",
        visitLive: "Visit live site",
        readCode: "Read the code",
        closeHint: "Esc to close",
        gallery: "Screens",
      },
      about: {
        index: "03",
        eyebrow: "About",
        heading: "I like problems that have a real person on the other end.",
        p1: "I'm a full-stack developer with five years of experience building web applications people actually use day to day.",
        p2: "My centre of gravity is the front end — React and Next.js, where I care about how fast a thing feels and how easy it stays to change six months later. I work across the backend too: APIs, databases and the server-side logic that makes a feature complete rather than a demo.",
        p3: "Most of my paid work has been building and shipping entire sites for Saudi companies — design through deployment, usually as the only developer on the project.",
        factsTitle: "Details",
        facts: {
          based: "Based in",
          basedValue: "Riyadh, Saudi Arabia",
          remote: "Working",
          remoteValue: "Remote, worldwide",
          timezone: "Timezone",
          timezoneValue: "GMT+3 (Riyadh)",
          languages: "Languages",
          languagesValue: "Arabic (native), English (professional)",
          status: "Status",
          statusValue: "Open to new projects and full-time roles",
        },
        skillsTitle: "What I work with",
        skillsNote:
          "Grouped by what I reach for first, not by what fills the most space.",
        groups: {
          frontend: "Front end",
          backend: "Backend & data",
          tooling: "Design & tooling",
        },
      },
      contact: {
        index: "04",
        eyebrow: "Contact",
        heading: "Let's build something.",
        lead: "Email is the fastest way to reach me — I read everything and reply within a day. Tell me what you're building and roughly when you need it.",
        formHeading: "Send a message",
        formLead:
          "Fill this in and it lands in my inbox. I'll reply to the address you give me.",
        directTitle: "Or reach me directly",
        elsewhere: "Elsewhere",
        form: {
          name: "Your name",
          namePlaceholder: "Jane Doe",
          email: "Your email",
          emailPlaceholder: "jane@company.com",
          emailHelp: "I'll reply here. It isn't used for anything else.",
          subject: "Subject",
          subjectPlaceholder: "New marketing site for a fintech",
          message: "Message",
          messagePlaceholder:
            "What are you building, what's the timeline, and what would success look like?",
          send: "Send message",
          sending: "Sending…",
          sent: "Message sent — I'll reply within a day.",
          failed:
            "That didn't send. Email me directly at ghzielmorhaf@gmail.com",
          errors: {
            name: "Please enter your name",
            email: "Please enter your email",
            emailInvalid: "That doesn't look like a valid email address",
            subject: "Please add a short subject",
            message: "Please write a message",
          },
        },
      },
      footer: {
        wordmark: "Murhaf Ghziel",
        tagline: "Full-stack developer. Riyadh, working worldwide.",
        builtWith: "Built with Next.js, Tailwind and Framer Motion.",
        copyright: "All rights reserved.",
        toTop: "Back to top",
      },
    },
  },

  ar: {
    name: "العربية",
    short: "ع",
    dir: "rtl",
    translations: {
      nav: {
        home: "الرئيسية",
        work: "الأعمال",
        about: "نبذة",
        contact: "تواصل",
        menu: "القائمة",
        close: "إغلاق",
      },
      status: {
        available: "متاح للعمل",
        location: "الرياض · توقيت +3",
      },
      cta: {
        seeWork: "شاهد الأعمال",
        downloadResume: "تحميل السيرة الذاتية",
        backHome: "العودة للرئيسية",
        copyEmail: "نسخ البريد",
        copied: "تم نسخ البريد",
        copyFailed: "تعذّر النسخ — البريد هو ghzielmorhaf@gmail.com",
      },
      hero: {
        fullName: "مرهف غزيل",
        line1: "مطوّر ويب",
        line2: "متكامل",
        line3: "يبني ويسلّم.",
        lead: "أنا مرهف. أصمّم وأبني تطبيقات ويب من البداية إلى النهاية — React وNext.js وTypeScript في الواجهة، وواجهات برمجية وقواعد بيانات خلفها. خمس سنوات خبرة، 15 مشروعاً منجزاً، منها 6 مشاريع لعملاء.",
        alt: "صورة مرهف غزيل",
      },
      ledger: {
        years: "سنوات خبرة",
        projects: "مشروع منجز",
        clients: "مشاريع لعملاء",
        reply: "زمن الرد",
        replyValue: "أقل من ٢٤ ساعة",
      },
      work: {
        index: "٢",
        eyebrow: "أعمال مختارة",
        heading: "كل ما بنيته، الأحدث أولاً.",
        help: "مرّر المؤشر على أي صف لمعاينته، واضغط لقراءة تفاصيل البناء.",
        helpTouch: "اضغط على أي صف لقراءة تفاصيل البناء.",
        filters: {
          all: "الكل",
          client: "أعمال العملاء",
          job: "دوام كامل",
          practice: "تدريب",
        },
        kind: {
          client: "عميل",
          job: "دوام كامل",
          practice: "تدريب",
        },
        empty: "لا يوجد شيء في هذا التصنيف بعد.",
        showAll: "عرض البقية",
        kindLabel: "النوع",
        role: "الدور",
        year: "السنة",
        overview: "نظرة عامة",
        visitLive: "زيارة الموقع",
        readCode: "قراءة الكود",
        closeHint: "اضغط Esc للإغلاق",
        gallery: "لقطات",
      },
      about: {
        index: "٣",
        eyebrow: "نبذة",
        heading: "أحبّ المشكلات التي خلفها مستخدم حقيقي.",
        p1: "مطوّر ويب متكامل بخبرة خمس سنوات في بناء تطبيقات يستخدمها الناس فعلياً كل يوم.",
        p2: "مركز ثقلي في الواجهة الأمامية — React وNext.js، حيث يهمّني كم تبدو سريعة وكم تبقى سهلة التعديل بعد ستة أشهر. وأعمل أيضاً على الواجهة الخلفية: واجهات برمجية وقواعد بيانات ومنطق الخادم الذي يحوّل الميزة من عرض تجريبي إلى شيء مكتمل.",
        p3: "معظم أعمالي المدفوعة كانت بناء مواقع كاملة لشركات سعودية — من التصميم حتى النشر، وغالباً كمطوّر وحيد في المشروع.",
        factsTitle: "تفاصيل",
        facts: {
          based: "المقر",
          basedValue: "الرياض، السعودية",
          remote: "طريقة العمل",
          remoteValue: "عن بُعد، عالمياً",
          timezone: "المنطقة الزمنية",
          timezoneValue: "توقيت الرياض (+3)",
          languages: "اللغات",
          languagesValue: "العربية (الأم)، الإنجليزية (احترافية)",
          status: "الحالة",
          statusValue: "متاح لمشاريع جديدة ووظائف بدوام كامل",
        },
        skillsTitle: "ما أعمل به",
        skillsNote: "مرتّبة حسب ما أستخدمه أولاً، لا حسب طول القائمة.",
        groups: {
          frontend: "الواجهة الأمامية",
          backend: "الخلفية والبيانات",
          tooling: "التصميم والأدوات",
        },
      },
      contact: {
        index: "٤",
        eyebrow: "تواصل",
        heading: "لنبنِ شيئاً معاً.",
        lead: "البريد الإلكتروني أسرع طريقة للوصول إليّ — أقرأ كل رسالة وأرد خلال يوم. أخبرني بما تبنيه وموعدك التقريبي.",
        formHeading: "أرسل رسالة",
        formLead: "املأ النموذج وستصلني الرسالة مباشرة. سأرد على البريد الذي تكتبه.",
        directTitle: "أو تواصل مباشرة",
        elsewhere: "روابط أخرى",
        form: {
          name: "الاسم",
          namePlaceholder: "محمد أحمد",
          email: "البريد الإلكتروني",
          emailPlaceholder: "you@company.com",
          emailHelp: "سأرد على هذا البريد فقط، ولن يُستخدم لأي شيء آخر.",
          subject: "الموضوع",
          subjectPlaceholder: "موقع تسويقي جديد لشركة مالية",
          message: "الرسالة",
          messagePlaceholder: "ما الذي تبنيه؟ وما الجدول الزمني؟ وكيف يبدو النجاح؟",
          send: "إرسال الرسالة",
          sending: "جارٍ الإرسال…",
          sent: "تم الإرسال — سأرد خلال يوم.",
          failed: "لم يتم الإرسال. راسلني مباشرة على ghzielmorhaf@gmail.com",
          errors: {
            name: "الرجاء إدخال اسمك",
            email: "الرجاء إدخال بريدك الإلكتروني",
            emailInvalid: "هذا لا يبدو بريداً إلكترونياً صحيحاً",
            subject: "الرجاء كتابة موضوع مختصر",
            message: "الرجاء كتابة رسالتك",
          },
        },
      },
      footer: {
        wordmark: "مرهف غزيل",
        tagline: "مطوّر ويب متكامل. الرياض، وأعمل عالمياً.",
        builtWith: "مبني بـ Next.js وTailwind وFramer Motion.",
        copyright: "جميع الحقوق محفوظة.",
        toTop: "العودة للأعلى",
      },
    },
  },
} as const;
