import type { Locale } from "./types";

/**
 * Every interface string, per language.
 *
 * Headlines use *asterisks* around the one word set in the italic serif.
 * Arabic is written for a Saudi reader, not translated from the English.
 */
const en = {
  meta: {
    title: "Murhaf Ghziel: websites people remember",
    description:
      "Designer and full-stack developer in Riyadh. Websites, stores and web apps, from first sketch to launch.",
    workTitle: "Work",
    workDescription: "Websites, stores and web apps designed and built by Murhaf Ghziel in Riyadh.",
  },
  skip: "Skip to content",
  nav: {
    work: "Work",
    services: "Services",
    about: "About",
    contact: "Contact",
    start: "Start a project",
    menu: "Menu",
    close: "Close",
    home: "Home",
    langSwitch: "ع",
    langSwitchLabel: "اقرأ بالعربية",
    toLight: "Switch to light mode",
    toDark: "Switch to dark mode",
  },
  hero: {
    title: "I design and build\nwebsites people\n*remember*.",
    lead: "I'm Murhaf, a designer and full-stack developer in Riyadh, crafting websites, stores and web apps from first sketch to launch.",
    viewWork: "View work",
    start: "Start a project",
    city: "Riyadh",
    scroll: "Scroll",
  },
  reel: {
    label: "Showreel — 2026",
    play: "Play full screen",
    close: "Close",
    caption: "Real screens from live projects.",
  },
  work: {
    title: "Selected *work*",
    all: "All",
    filters: { websites: "Websites", ecommerce: "E-commerce", webapps: "Web apps" },
    kind: { client: "Client", job: "Full-time role", personal: "Own product", studio: "My studio" },
    viewAll: "View all work",
    empty: "Nothing here yet.",
    pageTitle: "All *work*",
    pageLead: "Every project, newest thinking first. Client work, a full-time role, and products I run myself.",
    grid: "Grid",
    list: "List",
    open: "Open case study",
  },
  services: {
    title: "What I *do*",
    items: [
      {
        name: "Websites & landing pages",
        line: "Company sites and launch pages, Arabic-first and fast.",
        deliverables: ["Design in Figma", "English and Arabic build", "Motion and interaction", "SEO and analytics"],
        projects: ["omdah", "inno", "iedar"],
      },
      {
        name: "E-commerce",
        line: "Stores that take real payments: mada, Apple Pay, STC Pay.",
        deliverables: ["Storefront design", "Checkout and payments", "Admin dashboard", "Order emails and tracking"],
        projects: ["etar"],
      },
      {
        name: "Web apps & platforms",
        line: "Dashboards, SaaS and internal tools with a real backend.",
        deliverables: ["Sign-in and roles", "Databases and APIs", "AI features", "Admin and CMS"],
        projects: ["archy", "ai-cv-generator", "alpha-factory"],
      },
      {
        name: "Interactive & motion",
        line: "Scroll scenes, WebGL and hand-built animation that stays fast.",
        deliverables: ["Scroll-driven scenes", "WebGL and shaders", "SVG animation", "Performance budgets"],
        projects: ["inno", "omdah"],
      },
    ],
  },
  process: {
    title: "How I *work*",
    steps: [
      { name: "Discover", line: "Understand the brand, the goal and who it's for." },
      { name: "Design", line: "Concept, art direction and the key screens." },
      { name: "Build", line: "Development, motion, and testing on real devices." },
      { name: "Launch", line: "Go live, then support and improve." },
    ],
  },
  about: {
    title: "Behind the *work*",
    lines: [
      "I'm Murhaf, a designer and full-stack developer based in Riyadh.",
      "Most of my paid work is whole sites for Saudi companies, from design to deployment, usually as the only developer on the project.",
      "In my work Arabic is never a mirror of the English. It's designed first.",
      "I care how fast a thing feels, and how easy it stays to change six months later.",
    ],
    portraitAlt: "Portrait of Murhaf Ghziel",
    tools: "Tools",
    elsewhere: "Elsewhere",
    cv: "Download CV",
  },
  contact: {
    title: "Let's build something *unforgettable*.",
    lead: "Tell me what you're building. I reply",
    email: "Email",
    copy: "Copy",
    copied: "Copied",
    whatsapp: "WhatsApp",
    whatsappOpen: "Open chat",
    whatsappText: "Hi Murhaf, I'd like to talk about a project.",
    formTitle: "Or send the details",
    name: "Name",
    emailField: "Email",
    type: "Project type",
    types: { website: "Website", ecommerce: "E-commerce", webapp: "Web app", interactive: "Interactive / 3D", other: "Other" },
    budget: "Budget",
    timeline: "Timeline",
    message: "Message",
    messagePh: "What are you building, and what would success look like?",
    send: "Send message",
    sending: "Sending…",
    success: "Message sent. I'll reply",
    errors: {
      name: "Please enter your name.",
      email: "Please enter a valid email.",
      type: "Pick a project type.",
      message: "Tell me a little about the project.",
      server: "It didn't send. Please email me directly:",
    },
    optional: "optional",
  },
  footer: {
    top: "Back to top",
    rights: "Riyadh",
  },
  caseStudy: {
    client: "Client",
    personal: "Own product",
    year: "Year",
    role: "Role",
    services: "Services",
    stack: "Stack",
    live: "Visit live site",
    code: "Code",
    challenge: "The challenge",
    idea: "The idea",
    screens: "Key screens",
    motion: "In motion",
    mobile: "On the phone",
    results: "Results",
    next: "Next project",
    notes: "Read the full build notes",
    back: "All work",
    start: "Start a project",
  },
  notFound: { title: "This page doesn't *exist*.", back: "Back home" },
};

type Copy = typeof en;

const ar: Copy = {
  meta: {
    title: "مرهف غزيل: مواقع تبقى في الذاكرة",
    description: "مصمّم ومطوّر ويب في الرياض. مواقع ومتاجر وتطبيقات ويب، من أول فكرة إلى الإطلاق.",
    workTitle: "الأعمال",
    workDescription: "مواقع ومتاجر وتطبيقات ويب صمّمها وبناها مرهف غزيل في الرياض.",
  },
  skip: "انتقل إلى المحتوى",
  nav: {
    work: "الأعمال",
    services: "الخدمات",
    about: "عنّي",
    contact: "تواصل",
    start: "ابدأ مشروعك",
    menu: "القائمة",
    close: "إغلاق",
    home: "الرئيسية",
    langSwitch: "EN",
    langSwitchLabel: "Read in English",
    toLight: "الوضع الفاتح",
    toDark: "الوضع الداكن",
  },
  hero: {
    title: "أصمّم وأبني مواقع\n*تبقى* في الذاكرة.",
    lead: "أنا مرهف، مصمّم ومطوّر ويب في الرياض. أبني مواقع ومتاجر وتطبيقات ويب، من أول فكرة إلى يوم الإطلاق.",
    viewWork: "شوف الأعمال",
    start: "ابدأ مشروعك",
    city: "الرياض",
    scroll: "انزل",
  },
  reel: {
    label: "العرض — ٢٠٢٦",
    play: "شغّل بملء الشاشة",
    close: "إغلاق",
    caption: "لقطات حقيقية من مشاريع شغّالة.",
  },
  work: {
    title: "أعمال *مختارة*",
    all: "الكل",
    filters: { websites: "مواقع", ecommerce: "متاجر", webapps: "تطبيقات ويب" },
    kind: { client: "عميل", job: "وظيفة بدوام كامل", personal: "منتج خاص", studio: "استوديوي" },
    viewAll: "كل الأعمال",
    empty: "ما فيه شيء هنا للحين.",
    pageTitle: "كل *الأعمال*",
    pageLead: "كل المشاريع في مكان واحد: أعمال لعملاء، ووظيفة بدوام كامل، ومنتجات أشغّلها بنفسي.",
    grid: "شبكة",
    list: "قائمة",
    open: "افتح المشروع",
  },
  services: {
    title: "وش *أسوّي*",
    items: [
      {
        name: "مواقع وصفحات هبوط",
        line: "مواقع شركات وصفحات إطلاق، تبدأ من العربي وسريعة.",
        deliverables: ["تصميم على Figma", "بناء بالعربي والإنجليزي", "حركة وتفاعل", "تهيئة لمحركات البحث وتحليلات"],
        projects: ["omdah", "inno", "iedar"],
      },
      {
        name: "متاجر إلكترونية",
        line: "متاجر تستقبل دفع حقيقي: مدى و Apple Pay و STC Pay.",
        deliverables: ["تصميم واجهة المتجر", "الدفع والسلة", "لوحة تحكم", "رسائل الطلب والتتبع"],
        projects: ["etar"],
      },
      {
        name: "تطبيقات ويب ومنصات",
        line: "لوحات تحكم ومنتجات SaaS وأدوات داخلية بخلفية حقيقية.",
        deliverables: ["تسجيل دخول وصلاحيات", "قواعد بيانات وواجهات برمجية", "ميزات ذكاء اصطناعي", "لوحة إدارة ومحتوى"],
        projects: ["archy", "ai-cv-generator", "alpha-factory"],
      },
      {
        name: "تفاعل وحركة",
        line: "مشاهد مع التمرير و WebGL وحركة مبنية يدوياً وتظل سريعة.",
        deliverables: ["مشاهد مرتبطة بالتمرير", "WebGL وشيدرز", "حركة SVG", "ميزانية أداء"],
        projects: ["inno", "omdah"],
      },
    ],
  },
  process: {
    title: "كيف *أشتغل*",
    steps: [
      { name: "أفهم", line: "أفهم العلامة والهدف ولمين الموقع." },
      { name: "أصمّم", line: "الفكرة والاتجاه البصري والشاشات الأساسية." },
      { name: "أبني", line: "التطوير والحركة والتجربة على أجهزة حقيقية." },
      { name: "أطلق", line: "ننزل الموقع، وبعدها دعم وتحسين." },
    ],
  },
  about: {
    title: "ورا *الشغل*",
    lines: [
      "أنا مرهف، مصمّم ومطوّر ويب متكامل في الرياض.",
      "أغلب شغلي المدفوع مواقع كاملة لشركات سعودية، من التصميم للنشر، وغالباً أكون المطوّر الوحيد في المشروع.",
      "العربي عندي مو نسخة معكوسة من الإنجليزي. أصمّمه أول.",
      "يهمّني الموقع كيف يحسّ بالسرعة، وكيف يظل سهل التعديل بعد ستة أشهر.",
    ],
    portraitAlt: "صورة مرهف غزيل",
    tools: "الأدوات",
    elsewhere: "حساباتي",
    cv: "تحميل السيرة الذاتية",
  },
  contact: {
    title: "خلنا نبني شيء *ما يُنسى*.",
    lead: "قل لي وش تبني. أرد عليك",
    email: "البريد",
    copy: "نسخ",
    copied: "تم النسخ",
    whatsapp: "واتساب",
    whatsappOpen: "افتح المحادثة",
    whatsappText: "هلا مرهف، أبي أتكلم معك عن مشروع.",
    formTitle: "أو أرسل التفاصيل",
    name: "الاسم",
    emailField: "البريد الإلكتروني",
    type: "نوع المشروع",
    types: { website: "موقع", ecommerce: "متجر", webapp: "تطبيق ويب", interactive: "تفاعلي / ثلاثي الأبعاد", other: "غير ذلك" },
    budget: "الميزانية",
    timeline: "المدة",
    message: "الرسالة",
    messagePh: "وش تبني؟ وكيف تعرف إنه نجح؟",
    send: "أرسل",
    sending: "جارٍ الإرسال…",
    success: "وصلت رسالتك. أرد عليك",
    errors: {
      name: "اكتب اسمك.",
      email: "اكتب بريد صحيح.",
      type: "اختر نوع المشروع.",
      message: "اكتب لي شوي عن المشروع.",
      server: "ما انرسلت. راسلني مباشرة على:",
    },
    optional: "اختياري",
  },
  footer: {
    top: "للأعلى",
    rights: "الرياض",
  },
  caseStudy: {
    client: "العميل",
    personal: "منتج خاص",
    year: "السنة",
    role: "الدور",
    services: "الخدمات",
    stack: "التقنيات",
    live: "زيارة الموقع",
    code: "الكود",
    challenge: "التحدي",
    idea: "الفكرة",
    screens: "الشاشات",
    motion: "بالحركة",
    mobile: "على الجوال",
    results: "النتائج",
    next: "المشروع التالي",
    notes: "اقرأ تفاصيل البناء كاملة",
    back: "كل الأعمال",
    start: "ابدأ مشروعك",
  },
  notFound: { title: "هذي الصفحة *مو موجودة*.", back: "الرئيسية" },
};

export const COPY: Record<Locale, Copy> = { en, ar };
export type { Copy };
