import type { Locale } from "./types";

/**
 * Every interface string, per language.
 *
 * Headlines use *asterisks* around the one word set in the italic serif.
 * Arabic is written for a Saudi reader, not translated from the English.
 */
const en = {
  meta: {
    title: "Murhaf Ghziel · Full-Stack Developer (Next.js, React)",
    description:
      "Full-stack developer who also designs. SaaS, websites and stores, from first sketch to launch.",
    workTitle: "Work",
    workDescription: "Websites, stores and web apps built by Murhaf Ghziel.",
  },
  skip: "Skip to content",
  nav: {
    work: "Work",
    services: "Services",
    about: "About",
    contact: "Contact",
    start: "Start a project",
    menu: "Menu",
    close: "Close",
    home: "Home",
    langSwitch: "ع",
    langSwitchLabel: "اقرأ بالعربية",
    toLight: "Switch to light mode",
    toDark: "Switch to dark mode",
  },
  hero: {
    title: "I build websites\npeople *remember*.",
    lead: "I'm Murhaf, a full-stack developer who designs what he builds: SaaS, websites and stores, from first sketch to launch.",
    viewWork: "View work",
    start: "Start a project",
    city: "Riyadh",
    scroll: "Scroll",
  },
  reel: {
    label: "Showreel — 2026",
    play: "Play full screen",
    close: "Close",
    caption: "Real screens from live projects.",
  },
  work: {
    title: "Selected *work*",
    all: "All",
    filters: { websites: "Websites", ecommerce: "E-commerce", webapps: "Web apps" },
    kind: { client: "Client", job: "Full-time role", personal: "Own product", studio: "My studio" },
    viewAll: "View all work",
    empty: "Nothing here yet.",
    pageTitle: "All *work*",
    pageLead: "Every project, newest thinking first. Client work, a full-time role, and products I run myself.",
    grid: "Grid",
    list: "List",
    open: "Open case study",
  },
  services: {
    title: "What I *do*",
    items: [
      {
        name: "SaaS & web apps",
        line: "Full SaaS products, from sign-up to billing: accounts, teams, dashboards and a real backend.",
        deliverables: ["Accounts, teams and roles", "Payments and invoicing", "Dashboards and admin", "AI features and APIs"],
        projects: ["alpha-factory", "lumen", "ai-cv-generator", "archy"],
      },
      {
        name: "Websites & landing pages",
        line: "Company sites and launch pages that load fast and read well in any language.",
        deliverables: ["English and Arabic build", "CMS so you can edit", "Motion and interaction", "SEO and analytics"],
        projects: ["sima", "omdah", "inno", "iedar", "elsina3ya"],
      },
      {
        name: "E-commerce",
        line: "Stores that take real payments: mada, Apple Pay, STC Pay.",
        deliverables: ["Storefront build", "Checkout and payments", "Admin dashboard", "Order emails and tracking"],
        projects: ["etar", "MERIT", "NASAQ"],
      },
      {
        name: "Interactive & 3D",
        line: "3D product experiences, scroll scenes and hand-built animation that stays fast.",
        deliverables: ["3D product viewers", "Scroll-driven scenes", "WebGL and shaders", "Performance budgets"],
        projects: ["MERIT", "NASAQ", "inno"],
      },
    ],
  },
  process: {
    title: "How I *work*",
    steps: [
      { name: "Discover", line: "Understand the brand, the goal and who it's for." },
      { name: "Design", line: "Concept, art direction and the key screens." },
      { name: "Build", line: "Development, motion, and testing on real devices." },
      { name: "Launch", line: "Go live, then support and improve." },
    ],
  },
  about: {
    title: "Behind the *work*",
    lines: [
      "I'm Murhaf, a full-stack developer with a designer's eye.",
      "Most of my paid work is SaaS platforms and whole sites, from the first screen to deployment.",
      "In my work Arabic is never a mirror of the English. It's designed first.",
      "I care how fast a thing feels, and how easy it stays to change six months later.",
    ],
    portraitAlt: "Portrait of Murhaf Ghziel",
    tools: "Tools",
    elsewhere: "Elsewhere",
    cv: "Download CV",
    historyTitle: "Experience",
    history: [
      {
        role: "Founder",
        org: "SIMA Studio",
        when: "2026 – now",
        where: "Riyadh",
        line: "My studio: websites, stores and 3D product experiences, including MERIT and NASAQ.",
      },
      {
        role: "Frontend Lead",
        org: "INNO",
        when: "Oct 2025 – Sep 2026",
        where: "Riyadh · Full-time",
        line: "Led a team of 3 frontend developers. Rebuilt the bilingual company site, cutting runtime dependencies by 60%.",
      },
      {
        role: "Frontend Developer",
        org: "OnlyFounders",
        when: "Jun – Nov 2025",
        where: "Remote · Contract",
        line: "The frontend for a Web3 fundraising MVP: live on-chain data, multi-wallet support, no page reloads.",
      },
      {
        role: "Freelance Full-Stack Developer",
        org: "Independent",
        when: "2024 – now",
        where: "Remote",
        line: "7 paid client builds, including Etar, Alpha Factory, IEDAR, Omdah and Snaya.",
      },
      {
        role: "B.Sc. Computer Science",
        org: "Asia Pacific University",
        when: "Graduated 2023",
        where: "Kuala Lumpur",
        line: "Bachelor's degree in Computer Science.",
      },
    ],
  },
  contact: {
    title: "Let's build something *unforgettable*.",
    lead: "Tell me what you're building. I reply",
    email: "Email",
    copy: "Copy",
    copied: "Copied",
    whatsapp: "WhatsApp",
    whatsappOpen: "Open chat",
    whatsappText: "Hi Murhaf, I'd like to talk about a project.",
    formTitle: "Or send the details",
    name: "Name",
    emailField: "Email",
    type: "Project type",
    types: { website: "Website", ecommerce: "E-commerce", webapp: "Web app", interactive: "Interactive / 3D", other: "Other" },
    budget: "Budget",
    timeline: "Timeline",
    message: "Message",
    messagePh: "What are you building, and what would success look like?",
    send: "Send message",
    sending: "Sending…",
    sentTitle: "Message sent.",
    sentLine: "Thanks. I'll reply {time} at",
    sendAnother: "Send another message",
    errors: {
      name: "Please enter your name.",
      email: "Please enter a valid email.",
      type: "Pick a project type.",
      message: "Tell me a little about the project.",
      server: "It didn't send. Please email me directly:",
    },
    optional: "optional",
  },
  footer: {
    top: "Back to top",
    rights: "Riyadh",
  },
  caseStudy: {
    client: "Client",
    personal: "Own product",
    year: "Year",
    role: "Role",
    services: "Services",
    stack: "Stack",
    live: "Visit live site",
    code: "Code",
    challenge: "The challenge",
    idea: "The idea",
    screens: "Key screens",
    motion: "In motion",
    mobile: "On the phone",
    results: "Results",
    next: "Next project",
    notes: "Read the full build notes",
    back: "All work",
    start: "Start a project",
  },
  notFound: { title: "This page doesn't *exist*.", back: "Back home" },
};

type Copy = typeof en;

const ar: Copy = {
  meta: {
    title: "مرهف غزيل · مطوّر ويب متكامل (Next.js, React)",
    description: "مطوّر ويب متكامل يصمّم كمان. منصات SaaS ومواقع ومتاجر، من أول فكرة إلى الإطلاق.",
    workTitle: "الأعمال",
    workDescription: "مواقع ومتاجر وتطبيقات ويب صمّمها وبناها مرهف غزيل.",
  },
  skip: "انتقل إلى المحتوى",
  nav: {
    work: "الأعمال",
    services: "الخدمات",
    about: "عنّي",
    contact: "تواصل",
    start: "ابدأ مشروعك",
    menu: "القائمة",
    close: "إغلاق",
    home: "الرئيسية",
    langSwitch: "EN",
    langSwitchLabel: "Read in English",
    toLight: "الوضع الفاتح",
    toDark: "الوضع الداكن",
  },
  hero: {
    title: "أبني مواقع\n*تبقى* في الذاكرة.",
    lead: "أنا مرهف، مطوّر ويب متكامل، وأصمّم اللي أبنيه: منصات SaaS ومواقع ومتاجر، من أول فكرة إلى يوم الإطلاق.",
    viewWork: "شوف الأعمال",
    start: "ابدأ مشروعك",
    city: "الرياض",
    scroll: "انزل",
  },
  reel: {
    label: "العرض — ٢٠٢٦",
    play: "شغّل بملء الشاشة",
    close: "إغلاق",
    caption: "لقطات حقيقية من مشاريع شغّالة.",
  },
  work: {
    title: "أعمال *مختارة*",
    all: "الكل",
    filters: { websites: "مواقع", ecommerce: "متاجر", webapps: "تطبيقات ويب" },
    kind: { client: "عميل", job: "وظيفة بدوام كامل", personal: "منتج خاص", studio: "استوديوي" },
    viewAll: "كل الأعمال",
    empty: "ما فيه شيء هنا للحين.",
    pageTitle: "كل *الأعمال*",
    pageLead: "كل المشاريع في مكان واحد: أعمال لعملاء، ووظيفة بدوام كامل، ومنتجات أشغّلها بنفسي.",
    grid: "شبكة",
    list: "قائمة",
    open: "افتح المشروع",
  },
  services: {
    title: "وش *أسوّي*",
    items: [
      {
        name: "منتجات SaaS وتطبيقات ويب",
        line: "منتجات SaaS كاملة، من التسجيل للاشتراك والدفع: حسابات وفرق ولوحات تحكم وخلفية حقيقية.",
        deliverables: ["حسابات وفرق وصلاحيات", "دفع وفواتير", "لوحات تحكم وإدارة", "ذكاء اصطناعي وواجهات برمجية"],
        projects: ["alpha-factory", "lumen", "ai-cv-generator", "archy"],
      },
      {
        name: "مواقع وصفحات هبوط",
        line: "مواقع شركات وصفحات إطلاق، سريعة وتنقرأ صح بأي لغة.",
        deliverables: ["بناء بالعربي والإنجليزي", "لوحة محتوى تعدّل منها", "حركة وتفاعل", "تهيئة لمحركات البحث وتحليلات"],
        projects: ["sima", "omdah", "inno", "iedar", "elsina3ya"],
      },
      {
        name: "متاجر إلكترونية",
        line: "متاجر تستقبل دفع حقيقي: مدى و Apple Pay و STC Pay.",
        deliverables: ["بناء واجهة المتجر", "الدفع والسلة", "لوحة تحكم", "رسائل الطلب والتتبع"],
        projects: ["etar", "MERIT", "NASAQ"],
      },
      {
        name: "تفاعل وثلاثي الأبعاد",
        line: "تجارب منتجات ثلاثية الأبعاد ومشاهد مع التمرير وحركة مبنية يدوياً وتظل سريعة.",
        deliverables: ["عارض منتجات ثلاثي الأبعاد", "مشاهد مرتبطة بالتمرير", "WebGL وشيدرز", "ميزانية أداء"],
        projects: ["MERIT", "NASAQ", "inno"],
      },
    ],
  },
  process: {
    title: "كيف *أشتغل*",
    steps: [
      { name: "أفهم", line: "أفهم العلامة والهدف ولمين الموقع." },
      { name: "أصمّم", line: "الفكرة والاتجاه البصري والشاشات الأساسية." },
      { name: "أبني", line: "التطوير والحركة والتجربة على أجهزة حقيقية." },
      { name: "أطلق", line: "ننزل الموقع، وبعدها دعم وتحسين." },
    ],
  },
  about: {
    title: "ورا *الشغل*",
    lines: [
      "أنا مرهف، مطوّر ويب متكامل وعندي عين مصمّم.",
      "أغلب شغلي المدفوع منصات SaaS ومواقع كاملة، من أول شاشة للنشر.",
      "العربي عندي مو نسخة معكوسة من الإنجليزي. أصمّمه أول.",
      "يهمّني الموقع كيف يحسّ بالسرعة، وكيف يظل سهل التعديل بعد ستة أشهر.",
    ],
    portraitAlt: "صورة مرهف غزيل",
    tools: "الأدوات",
    elsewhere: "حساباتي",
    cv: "تحميل السيرة الذاتية",
    historyTitle: "الخبرة",
    history: [
      {
        role: "المؤسس",
        org: "سِمة",
        when: "٢٠٢٦ – الآن",
        where: "الرياض",
        line: "استوديوي: مواقع ومتاجر وتجارب منتجات ثلاثية الأبعاد، منها MERIT و NASAQ.",
      },
      {
        role: "قائد فريق الواجهات",
        org: "اينو",
        when: "أكتوبر ٢٠٢٥ – سبتمبر ٢٠٢٦",
        where: "الرياض · دوام كامل",
        line: "قدت فريق من ٣ مطورين واجهات. أعدت بناء موقع الشركة ثنائي اللغة وخفّضت اعتمادات التشغيل ٦٠٪.",
      },
      {
        role: "مطوّر واجهات",
        org: "OnlyFounders",
        when: "يونيو – نوفمبر ٢٠٢٥",
        where: "عن بُعد · عقد",
        line: "واجهة منصة تمويل Web3: بيانات مباشرة من البلوكتشين، وأكثر من محفظة، بدون إعادة تحميل.",
      },
      {
        role: "مطوّر ويب متكامل مستقل",
        org: "مستقل",
        when: "٢٠٢٤ – الآن",
        where: "عن بُعد",
        line: "٧ مشاريع مدفوعة لعملاء، منها إطار وألفا فاكتوري وأيدار وعُمدة والصناعية.",
      },
      {
        role: "بكالوريوس علوم الحاسب",
        org: "جامعة آسيا والمحيط الهادئ",
        when: "تخرجت ٢٠٢٣",
        where: "كوالالمبور",
        line: "بكالوريوس في علوم الحاسب.",
      },
    ],
  },
  contact: {
    title: "خلنا نبني شيء *ما يُنسى*.",
    lead: "قل لي وش تبني. أرد عليك",
    email: "البريد",
    copy: "نسخ",
    copied: "تم النسخ",
    whatsapp: "واتساب",
    whatsappOpen: "افتح المحادثة",
    whatsappText: "هلا مرهف، أبي أتكلم معك عن مشروع.",
    formTitle: "أو أرسل التفاصيل",
    name: "الاسم",
    emailField: "البريد الإلكتروني",
    type: "نوع المشروع",
    types: { website: "موقع", ecommerce: "متجر", webapp: "تطبيق ويب", interactive: "تفاعلي / ثلاثي الأبعاد", other: "غير ذلك" },
    budget: "الميزانية",
    timeline: "المدة",
    message: "الرسالة",
    messagePh: "وش تبني؟ وكيف تعرف إنه نجح؟",
    send: "أرسل",
    sending: "جارٍ الإرسال…",
    sentTitle: "وصلت رسالتك.",
    sentLine: "شكراً لك. أرد عليك {time} على",
    sendAnother: "أرسل رسالة ثانية",
    errors: {
      name: "اكتب اسمك.",
      email: "اكتب بريد صحيح.",
      type: "اختر نوع المشروع.",
      message: "اكتب لي شوي عن المشروع.",
      server: "ما انرسلت. راسلني مباشرة على:",
    },
    optional: "اختياري",
  },
  footer: {
    top: "للأعلى",
    rights: "الرياض",
  },
  caseStudy: {
    client: "العميل",
    personal: "منتج خاص",
    year: "السنة",
    role: "الدور",
    services: "الخدمات",
    stack: "التقنيات",
    live: "زيارة الموقع",
    code: "الكود",
    challenge: "التحدي",
    idea: "الفكرة",
    screens: "الشاشات",
    motion: "بالحركة",
    mobile: "على الجوال",
    results: "النتائج",
    next: "المشروع التالي",
    notes: "اقرأ تفاصيل البناء كاملة",
    back: "كل الأعمال",
    start: "ابدأ مشروعك",
  },
  notFound: { title: "هذي الصفحة *مو موجودة*.", back: "الرئيسية" },
};

export const COPY: Record<Locale, Copy> = { en, ar };
export type { Copy };
